[package]
name = "first_counter"
description = "A TON blockchain project"
version = "0.1.0"
license = "MIT"

[toolchain]
acton = "1.0.0"

[contracts.Counter]
display-name = "Counter"
src = "contracts/src/Counter.tolk"
depends = []

[contracts.StonFiSwap]
display-name = "StonFiSwap"
src = "contracts/src/StonFiSwap.tolk"
depends = []

[test]

[fmt]
width = 100
ignore = []

[scripts]
deploy-emulation = "acton script contracts/scripts/deploy.tolk"
deploy-testnet = "acton script contracts/scripts/deploy.tolk --net testnet"
stonfi-swap-emulation = "acton script contracts/scripts/stonfi_swap.tolk"
stonfi-swap-testnet = "acton script contracts/scripts/stonfi_swap.tolk --net testnet"
stonfi-swap-testnet-tonconnect = "acton script contracts/scripts/stonfi_swap.tolk --net testnet --tonconnect"
stonfi-swap-setup-emulation = "acton script contracts/scripts/stonfi_swap_setup.tolk"
stonfi-swap-setup-testnet = "acton script contracts/scripts/stonfi_swap_setup.tolk --net testnet"
stonfi-swap-setup-testnet-tonconnect = "acton script contracts/scripts/stonfi_swap_setup.tolk --net testnet --tonconnect"
stonfi-swap-setup-existing-emulation = "acton script contracts/scripts/stonfi_swap_setup_existing.tolk"
stonfi-swap-setup-existing-testnet = "acton script contracts/scripts/stonfi_swap_setup_existing.tolk --net testnet"
stonfi-swap-smoke-emulation = "acton script contracts/scripts/stonfi_swap_smoke.tolk"
stonfi-swap-smoke-testnet = "acton script contracts/scripts/stonfi_swap_smoke.tolk --net testnet"
stonfi-swap-smoke-testnet-tonconnect = "acton script contracts/scripts/stonfi_swap_smoke.tolk --net testnet --tonconnect"
stonfi-swap-smoke-existing-emulation = "acton script contracts/scripts/stonfi_swap_smoke_existing.tolk"
stonfi-swap-smoke-existing-testnet = "acton script contracts/scripts/stonfi_swap_smoke_existing.tolk --net testnet"

[import-mappings]
acton = ".acton"
contracts = "contracts/src"
gen = "gen"
tests = "contracts/tests"
wrappers = "contracts/wrappers"

# Check full Acton.toml reference and all available keys:
# https://ton-blockchain.github.io/acton/docs/acton-toml
